image: maven:3.9.6-eclipse-temurin-11

stages:
  - build
  - docker
  - test

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests"
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:k6-generator

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package

docker_build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $DOCKER_IMAGE
  only:
    - main

run_test:
  stage: test
  image: curlimages/curl:8.6.0
  services:
    - name: docker:dind
  script:
    - docker run -d -p 8080:8080 -v $(pwd)/output:/app/output $DOCKER_IMAGE
    - sleep 10
    - curl "http://localhost:8080/api/k6/generate?https://new-api.maps.itsrv.xyz/v1-api-swagger=https://petstore3.swagger.io/api/v3/openapi.json&bearerToken=DGPu5_xebwt6hn-pCSrUSBZOHLt5cCOS6synrMioOYsnPdL46YQk-MvpopNsM7I4"
    - echo "Generated script content:"
    - cat output/generatedK6Script.txt
  only:
    - main